module.exports = {
  "jsRules": {
    // https://palantir.github.io/tslint/rules/ban/
    "ban": false,
    // https://palantir.github.io/tslint/rules/curly/
    "curly": [true, "ignore-same-line"],
    // https://palantir.github.io/tslint/rules/forin/
    "forin": false,
    // https://palantir.github.io/tslint/rules/import-blacklist/
    "import-blacklist": false,
    // https://palantir.github.io/tslint/rules/label-position/
    "label-position": true,
    // https://palantir.github.io/tslint/rules/no-arg/
    "no-arg": true,
    // https://palantir.github.io/tslint/rules/no-bitwise/
    "no-bitwise": false,
    // https://palantir.github.io/tslint/rules/no-conditional-assignment/
    "no-conditional-assignment": true,
    // https://palantir.github.io/tslint/rules/no-console/
    "no-console": false,
     // https://palantir.github.io/tslint/rules/no-construct/
    "no-construct": true,
    // https://palantir.github.io/tslint/rules/no-debugger/
    "no-debugger": false,
    // https://palantir.github.io/tslint/rules/no-duplicate-super/
    "no-duplicate-super": true,
    // https://palantir.github.io/tslint/rules/no-duplicate-variable/
    "no-duplicate-variable": true,
    // https://palantir.github.io/tslint/rules/no-empty/
    "no-empty": true,
    // https://palantir.github.io/tslint/rules/no-eval/
    "no-eval": true,
    // https://palantir.github.io/tslint/rules/no-for-in-array/
    "no-for-in-array": true,
    // https://palantir.github.io/tslint/rules/no-invalid-template-strings/
    "no-invalid-template-strings": true,
    // https://palantir.github.io/tslint/rules/no-invalid-this/
    "no-invalid-this": true,
    // https://palantir.github.io/tslint/rules/no-null-keyword/
    "no-null-keyword": true,
    // https://palantir.github.io/tslint/rules/no-shadowed-variable/
    "no-shadowed-variable": true,
    // https://palantir.github.io/tslint/rules/no-sparse-arrays/
    "no-sparse-arrays": false,
    // https://palantir.github.io/tslint/rules/no-string-literal/
    "no-string-literal": false,
    // https://palantir.github.io/tslint/rules/no-string-throw/
    "no-string-throw": true,
    // https://palantir.github.io/tslint/rules/no-switch-case-fall-through/
    "no-switch-case-fall-through": true,
  },
  "rules": {
    // https://palantir.github.io/tslint/rules/await-promise/
    "await-promise": false,
    // https://palantir.github.io/tslint/rules/ban/
    "ban": false,
    // https://palantir.github.io/tslint/rules/curly/
    "curly": [true, "ignore-same-line"],
    // https://palantir.github.io/tslint/rules/forin/
    "forin": false,
    // https://palantir.github.io/tslint/rules/import-blacklist/
    "import-blacklist": false,
    // https://palantir.github.io/tslint/rules/label-position/
    "label-position": true,
    // https://palantir.github.io/tslint/rules/no-arg/
    "no-arg": true,
    // https://palantir.github.io/tslint/rules/no-bitwise/
    "no-bitwise": false,
    // https://palantir.github.io/tslint/rules/no-conditional-assignment/
    "no-conditional-assignment": true,
    // https://palantir.github.io/tslint/rules/no-console/
    "no-console": false,
    // https://palantir.github.io/tslint/rules/no-construct/
    "no-construct": true,
    // https://palantir.github.io/tslint/rules/no-debugger/
    "no-debugger": false,
    // https://palantir.github.io/tslint/rules/no-duplicate-super/
    "no-duplicate-super": true,
    // https://palantir.github.io/tslint/rules/no-duplicate-variable/
    "no-duplicate-variable": true,
    // https://palantir.github.io/tslint/rules/no-empty/
    "no-empty": true,
    // https://palantir.github.io/tslint/rules/no-eval/
    "no-eval": true,
    // https://palantir.github.io/tslint/rules/no-floating-promises/
    "no-floating-promises": true,
    // https://palantir.github.io/tslint/rules/no-for-in-array/
    "no-for-in-array": true,
    // https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/
    "no-inferred-empty-object-type": true,
    // https://palantir.github.io/tslint/rules/no-invalid-template-strings/
    "no-invalid-template-strings": true,
    // https://palantir.github.io/tslint/rules/no-invalid-this/
    "no-invalid-this": true,
    // https://palantir.github.io/tslint/rules/no-null-keyword/
    "no-null-keyword": true,
    // https://palantir.github.io/tslint/rules/no-misused-new/
    "no-misused-new": true,
    // https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/
    "no-object-literal-type-assertion": true,
    // https://palantir.github.io/tslint/rules/no-shadowed-variable/
    "no-shadowed-variable": true,
    // https://palantir.github.io/tslint/rules/no-sparse-arrays/
    "no-sparse-arrays": false,
    // https://palantir.github.io/tslint/rules/no-string-literal/
    "no-string-literal": false,
    // https://palantir.github.io/tslint/rules/no-string-throw/
    "no-string-throw": true,
    // https://palantir.github.io/tslint/rules/no-switch-case-fall-through/
    "no-switch-case-fall-through": true,
  },
}
